name: Trading Bot Automation
on:
  schedule:
    - cron: '0 13 * * *' # Bot akan jalan setiap hari jam 9 pagi
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install yfinance ta requests
      - name: Run bot
        run: python simpan_harga.py
