name: Trading Bot Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '45 13 * * *' # Jam 9:45 PM MYT

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests yfinance pandas gtts
      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: python simpan_harga.py
